name: Update README activity

on:
  workflow_dispatch:     # 先手動觸發
  # schedule:
  #   - cron: "17 */6 * * *"   # 想開排程再打開

permissions:
  contents: write        # 讓內建 token 可以 commit README

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 這個 action 會更新下方兩個標記之間的內容：
      # <!--START_SECTION:activity--> ... <!--END_SECTION:activity-->
      - name: Update README with recent activity
        uses: Readme-Workflows/recent-activity@v2.4.1
        with:
          GH_TOKEN: ${{ secrets.REPO_TOKEN }}      # 你剛剛建立的 PAT
          MAX_LINES: 10                            # 顯示幾行（可調）
          COMMIT_MSG: "ci: update recent activity [skip ci]"
